"""Add active_metrics

Revision ID: 385b3823fd85
Revises: 511cb6e0b060
Create Date: 2025-03-30 12:39:18.816515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385b3823fd85'
down_revision: Union[str, None] = '511cb6e0b060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('active_based_on_pp', sa.BigInteger(), nullable=True),
    sa.Column('active_based_on_in_use', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_metrics')
    # ### end Alembic commands ###
