"""Add pp_tracking and resource_metrics table

Revision ID: 511cb6e0b060
Revises: 
Create Date: 2025-03-29 16:00:17.027892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511cb6e0b060'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pp_tracking',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('total_harvest_pp', sa.BigInteger(), nullable=True),
    sa.Column('total_base_pp_after_cap', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'resource')
    )
    op.create_table('resource_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('token_symbol', sa.String(), nullable=False),
    sa.Column('resource_quantity', sa.Float(), nullable=False),
    sa.Column('resource_volume', sa.Float(), nullable=False),
    sa.Column('resource_volume_1', sa.Float(), nullable=True),
    sa.Column('resource_volume_30', sa.Float(), nullable=True),
    sa.Column('resource_price', sa.Float(), nullable=False),
    sa.Column('dec_quantity', sa.Float(), nullable=False),
    sa.Column('dec_volume', sa.Float(), nullable=False),
    sa.Column('dec_volume_1', sa.Float(), nullable=True),
    sa.Column('dec_volume_30', sa.Float(), nullable=True),
    sa.Column('dec_price', sa.Float(), nullable=False),
    sa.Column('total_shares', sa.Float(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(), nullable=True),
    sa.Column('dec_usd_value', sa.Float(), nullable=False),
    sa.Column('grain_equivalent', sa.Float(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'token_symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_metrics')
    op.drop_table('pp_tracking')
    # ### end Alembic commands ###
